### ISSUE TITLE
fresh install, bad indentation after sync-from-trello

### ISSUE THREAD

**Issue by ptitjano** [org-trello/org-trello#242]
Hi,

I have just installed org-trello from melpa following the documentation.
When i try to import a board into a new org file (C-u C-c o s), the cards are imported but the indentation of the cards is broken. For example:

```txt
* Basics Welcome to Trello!
  :PROPERTIES...

  * Basics This is a card.
    :PROPERTIES...
```

I got two spaces before the second card and the next ones.
I'm using emacs 24.4.1 with org-mode 8.2.10
org-trello comes from melpa (v 20150208)

Steps to reproduce:
1. Open a new org file and load org-trello-mode
2. Connect the buffer to a board: C-c o I and choose "Welcome Board"
3. Sync from trello: C-u C-c o s

**Comment by ardumont** [comment]
Hello,

I have not the time right now to look into it but this seems like the bug in #232 again.

This is because the card 'Welcome to Trello!' is empty (no checklist)...
Definitely worth `seek and destroy` :metal: once and for all.

Sorry for the inconvenience and thanks for raising this up.

Cheers,

**Comment by ardumont** [comment]
Hello,

Some news about this. I do reproduce.

As in the sample you provided, when a card is empty (no description nor checkslist), the following card gets indented.
The indentation is part of org-trello but it is either for the description or for the current card's content (from checklist to items).
Not for the next card... 

There must be a mistake in the region computation.

Cheers,

**Comment by kstarsinic** [comment]
I'm seeing a similar problem. It seems that, for certain boards, every time I enter org-trello-mode the indentation increases for some cards. I have been trying to investigate, but I cannot figure out what code is modifying the buffer when org-trello-mode is enabled. In particular, I notice that orgtrello-controller/ functions are added to org-trello-mode-on-hook and org-trello-mode-off-hook, but according to the debugger, neither the -on- nor -off- hooks are being called. Can you explain? Using version 0.6.9.2.

**Comment by ardumont** [comment]
Hello,

> In particular, I notice that orgtrello-controller/ functions are added to org-trello-mode-on-hook and org-trello-mode-off-hook, but according to the debugger, neither the -on- nor -off- hooks are being called. Can you explain?

If those are not called, this is not the expected behavior indeed.

The on and off hook are [automatically defined by the define-minor-mode macro](https://github.com/org-trello/org-trello/blob/master/org-trello.el#L340). 

I do not have link for this but here is an extract from the `define-minor-mode` definition:
```lisp
(defmacro define-minor-mode (mode doc &optional init-value lighter keymap &rest body)
  "Define a new minor mode MODE.
This defines the toggle command MODE and (by default) a control variable
...
	 (hook (intern (concat mode-name "-hook")))
	 (hook-on (intern (concat mode-name "-on-hook")))
	 (hook-off (intern (concat mode-name "-off-hook")))
...
```

I use the [`orgtrello-controller/mode-on-hook-fn`](https://github.com/org-trello/org-trello/blob/master/org-trello.el#L350) to install actions to execute just before saving the buffer, install or update overlays to hide the checkboxes' metadata (id, checksum).
It's installed on the `org-trello-mode-on-hook` which is called at org-trello-mode activation.

The [`orgtrello-controller/mode-off-hook-fn`](https://github.com/org-trello/org-trello/blob/master/org-trello.el#L364) is the `symmetrical` one to uninstall what was installed with `on` hook.
It's installed on the `org-trello-mode-off-hook` which is called at org-trello-mode deactivation.

> I'm seeing a similar problem. It seems that, for certain boards, every time I enter org-trello-mode the indentation increases for some cards. I have been trying to investigate, but I cannot figure out what code is modifying the buffer when org-trello-mode is enabled.

Yes, this must be the same issue.

The code you are looking must be the call to `(orgtrello-controller/prepare-buffer!)`.
This function is also installed as a `before-save-hook`.
And after a sync from trello (as per the initial user said), this is called.
Thus the same error.

Also, this remark makes me understand that the actions undertook (via the hooks from the point before) seems to be installed...

> Using version 0.6.9.2.

Knowing your emacs version can help too (I personally use emacs-24.4).

-- 

You mention the use of the debugger, how do you do it?

Do you add a `(debug)` point and re-eval the function definition?

Thanks for your help!

Cheers,

**Comment by ardumont** [comment]
Ok.

I have found the culprit function `orgtrello-entity/compute-first-comment-point!`.
When a card contains no comment, it goes awry.

I now need some time to fix it.

Cheers,

**Comment by ardumont** [comment]
I've got something.
If someone could try and eval this on his/her emacs, it would be great to confirm:

Open a *scratch* buffer and placing the caret after the last `)` then `M-x eval-buffer` should monkey patch the actual problematic definition:
```lisp
(defun orgtrello-entity/compute-first-comment-point! ()
  "Compute the card's first comment position.
Does preserve position.
If no comment is found, return the card's end region."
  (save-excursion
    (orgtrello-entity/back-to-card!)
    (let ((card-region (orgtrello-entity/compute-card-region!)))
      (apply 'narrow-to-region card-region)
      (let ((next-pt (-if-let (next-pt (search-forward-regexp "[*][*] " nil t)) ;; if not found, return nil and do not move point
                         (save-excursion
                           (goto-char next-pt)
                           (point-at-bol))
                       (orgtrello-entity/compute-next-card-point!))))
        (widen)
        next-pt))))
```

Now try and load as usual.

Thanks for the help.

Cheers,

**Comment by ptitjano** [comment]
Hi,

I've just tried this patch with my current configuration and the Welcome Board.
The problem is solved. Thanks !

Cheers,

**Comment by ardumont** [comment]
Thanks!

Will push a 0.6.9.3 soon!
