### ISSUE TITLE
Changing order of checklist items not saved unless checklist item's text changed

### ISSUE THREAD

**Issue by erahhal** [org-trello/org-trello#250]
Right now I'm working around this by adding a space to the end of a checklist item then syncing to Trello, after which order is saved.

Order of cards is also not preserved/updated.

**Comment by ardumont** [comment]
Sorry I did not get back to you earlier.

It should.
I use the `pos` attribute from trello's api.
I will need some time to investigate this because 

As always, thanks for raising this up.

Cheers,

**Comment by ardumont** [comment]
When synchronizing to trello, the checklist, item order is not kept.
Worst, the order seems randomly set in trello card.

**Comment by ardumont** [comment]
Remembering now, I use the `pos` attribute in the http query and the value used is the position in the emacs buffer without doing anything special. 
Because even though, the position in the buffer was big number, it still respected the natural order.

It worked as is but now this seems to no longer be ok.

**Comment by ardumont** [comment]
I had a eureka moment (and I like those :D).

This behavior must be due to the checklist/item checksum computation (used for sending only modified data).

The position is not part of the checksum.
Thus changing the position does not change the checksum.
And the item state change alters the checksum of the item but also of the checklist.

Then the actual behavior (which, as said, also sends the position) does the rest.

So the actual fix is to add the position in the checksum computation (of all entities).
(I supose this is also true for card).

Cheers,

**Comment by ardumont** [comment]
Also, as suspected, simply changing the title of the checklist also does the trick.

**Comment by ardumont** [comment]
I was correct in my hypothesis.
I have a fix for this consistent bad behavior (all entities were a victim of this ; card, checklist, item).

```lisp
(defun orgtrello-buffer/compute-generic-checksum! (compute-region-fn)
  "Compute the entity's checksum.
COMPUTE-REGION-FN is the region computation function."
  (let ((region (funcall compute-region-fn))
        (buffer-name (current-buffer)))
    (with-temp-buffer
      (apply 'insert-buffer-substring (cons buffer-name region))
      (org-mode)
      (orgtrello-buffer/delete-property! org-trello--label-key-local-checksum)
      (insert (format "%s" region)) ;; take into account the position for the checksum
      (->> (list (point-min) (point-max))
           (cons (current-buffer))
           (cons 'sha256)
           (apply 'secure-hash)))))
```
I injected the region as part of the checksum computation.
Moving an entity is now detected and this triggers a trello request.

You can try it by copy/paste the following code inside a scratch buffer and evaluate it <kbd>M-x eval-buffer</kbd>.
This will monkey-patch your current loaded org-trello (not persisted after an emacs restart).

This of course has limits (as per the current code's behavior):
- move a card and the cards's content impacted by this move will be sent to trello
- move a checklist and the checklists' content impacted by this move will be sent to trello
- move an item and all the items' content impacted by this move will be sent to trello

Cheers,
