### ISSUE TITLE
Issues org-trello/install-board-metadata

### ISSUE THREAD

**Issue by benquike** [org-trello/org-trello#265]
When issuing  org-trello/install-board-metadata, the following message occured'
org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 6.

my org-trello version is  ｀org-trello - version: 0.6.9.6｀

**Comment by ardumont** [comment]
Hello,

> When issuing org-trello/install-board-metadata, the following message occured'
> org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 6.

> my org-trello version is ｀org-trello - version: 0.6.9.6｀

Ok. To have a little more information when in trouble, [this](http://org-trello.github.io/contributions.html#issues) helps :D.

Nonetheless, the code 6 may be curl relative
(may because the http client used in org-trello, `request` can use `curl` or another lib I do not remember depending on your platform).

Assuming it's curl, the error code 6 means 'could not resolve the host' (http://curl.haxx.se/libcurl/c/libcurl-errors.html).

As per this sample shows:
```sh
# tony at corellia in ~ [12:27:31]
$ curl http://foo
curl: (6) Could not resolve host: foo
```

I checked on my side that I'm stille able to connect to trello so it's not down (we never know...).
As a note, depending on the country, I guess this could change...

Can you reached `https://api.trello.com` with your browser?

Cheers,

**Comment by benquike** [comment]
> Can you reached https://api.trello.com with your browser?
I have checked using my browser, it works.

**Comment by ardumont** [comment]
Hello again,

Can you please try with curl?

```sh
curl -L https://api.trello.com
```
`-L` to follow the redirection.

Cheers,

**Comment by benquike** [comment]
hi, I have confirmed by running the following command in eshell mode.
It was that network connect did not work.
curl -L https://api.trello.com
```
curl: (6) Couldn't resolve host 'api.trello.com'
```

Many thanks

**Comment by benquike** [comment]
by the way, I use emacs on windows, and when I run curl -L https://api.trello.com fron Cygwin, it seems works, but when I run it from the eshell of emacs, it does not work, maybe some setting is needed in emacs

**Comment by ardumont** [comment]
Hello,

> by the way, I use emacs on windows, and when I run curl -L https://api.trello.com fron Cygwin, it seems works, but when I run it from the eshell of emacs, it does not work, maybe some setting is needed in emacs

Good you found out where the problem lies...
Alas, I am not fluent in windows...

Have you tried starting emacs from cygwin?
(If someone out there could help, this would be great!)

Cheers,
