### ISSUE TITLE
Rename sync -> push/pull

### ISSUE THREAD

**Issue by yangchenyun** [org-trello/org-trello#284]
sync usually means two way synchronization; current features more like a push / pull operation.

**Comment by ardumont** [comment]
Hello,

My goal at one point would be to `sync` - #59...

That's why i began to look at ar org-sync (http://orgmode.org/w/?p=org-sync.git, https://github.com/arbox/org-sync). To see how people do it.

In the meantime, you could use `defalias` on your install if that bothers you too much.

Something like this would do it:
```lisp
(defalias 'org-trello-push-buffer 'org-trello-sync-buffer)
(defalias 'org-trello-pull-buffer (lambda () (interactive) (org-trello-sync-buffer 'from)))
...
```

Cheers,
