### ISSUE TITLE
Not able to Sync 

### ISSUE THREAD

**Issue by Jesse-Millwood** [org-trello/org-trello#323]
I went through the install pretty well. I ran into the issue with using an email but found out to use my username from the the other issues. I can perform the `org-trello-create-board-and-install-metada` function. This creates a board that I can see in the browser with the cards that have the TODO labels I defined in my buffer variable with `#+TODO: TODO DOING | DONE FAIL`. But there is nothing in the cards. 

Here is my simple file after creating the board and installing the metadata:
```
:PROPERTIES:
#+PROPERTY: board-name FooBar
#+PROPERTY: board-id 56e...ca9
#+PROPERTY: FAIL 56e...e2f
#+PROPERTY: DONE 56e...e42
#+PROPERTY: DOING 56e...7f2
#+PROPERTY: TODO 56e...cb1
#+TODO: TODO DOING | DONE FAIL
#+PROPERTY: orgtrello-user-jessemillwood 54b...e06
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :red
#+PROPERTY: :orange
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: orgtrello-user-me jessemillwood
:END:
#+TODO: TODO DOING | DONE FAIL

* TODO First Heading
```
I expected to see a card called TODO with an entry that says "First Heading in it". This is what I see though:
![selection_004](https://cloud.githubusercontent.com/assets/5342237/13782258/04442304-ea8c-11e5-8ce9-d8d71011c627.png)

Now when I run `C-c o c` I get the error:
```
org-trello - List of errors:
 - Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello-install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)
```
I get this after performing the `C-c C-c` on the `#+TODO: TODO DOING | DONE FAIL` line as well. I believe I am connected to the board as can be seen in my `:PROPERTIES:` drawer. I feel that I followed all of the steps but I may be missing something. Any pointers are appreciated I may be just using this wrong. 

My info:
```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.7)
 of 2016-02-23
- org version: 8.3.4
- org-trello version: 0.7.8
- org-trello path: /home/acusar/.emacs.d/elpa/org-trello-20160301.941/org-trello.el
- request-backend: url-retrieve
```

Thank you for all the work you have done on this! It seems like a great tool once I get it going!

**Comment by Jesse-Millwood** [comment]
Never mind, 
The issue was that I had a `#+TODO: ......` line outside of the properties drawer at  the top. I realized it looked odd that there was another `#+TODO: .... ` line in the drawer and out of it.

**Comment by Jesse-Millwood** [comment]
I don't know if this is by design, so what would be the suggested work flow if I wanted a different set of card names? It seems that it would then have to be:

1. Type up org mode file
2. Add a #+TODO: line
3. Create board and install metadata
4. Delete original #+TODO line
5. Sync buffer

This seems fine I just want to make sure I'm not missing something.

Again, thanks for the great tool!

**Comment by ardumont** [comment]
Hello,

> Thank you for all the work you have done on this! It seems like a great tool once I get it going!

Thanks.

> ...
> Never mind,
> The issue was that I had a #+TODO: ...... line outside of the properties drawer at the top. I realized it looked odd that there was another #+TODO: .... line in the drawer and out of it. 

When installing the trello boards' metadata, the org keywords #+TODO (used to map the trello lists) are installed along. So indeed, no need for you to add them.

(Still i would not have guessed that having them in duplicates would create trouble...)

> I don't know if this is by design, so what would be the suggested work flow if I wanted a different set of card names? 

What you call trello card, i may wrongly call them trello list...

> It seems that it would then have to be:
>    Type up org mode file
>    Add a #+TODO: line
>    Create board and install metadata
>    Delete original #+TODO line
>    Sync buffer

Yes, that would be it.
I must admit, It's not completely by design...

It's also because org permits your to define local buffer keywords with the #+todo entry.

But there is at least one other way, org customization like https://github.com/ardumont/orgmode-pack/blob/master/orgmode-pack.el#L45.

Note that there is currently a limitation too.
org-trello cannot determine org terminal state (like DONE).
If you want to see in org the terminal state, you must add yourself the separator |

```
#+TODO: blah bloh bluf | foo oof 
```
Here foo and oof are treated as terminal states.
(i should have used like your sample DONE or FAIL here ^^).

> I went through the install pretty well. I ran into the issue with using an email but found out to use my username from the the other issues.

Also, do you think that this step http://org-trello.github.io/trello-setup.html can be better explained?

quote: 
```
This command will:

    ask for an account name which must be your trello login. Check https://trello.com/**your-user-login** where your-user-login is the login you must use.
```

I tried to explicit it some time ago but apparently it's not enough.

Anyway,  thanks for the neat report.

Cheers,
