### ISSUE TITLE
Spurious PROPERTIES in description

### ISSUE THREAD

**Issue by arichiardi** [org-trello/org-trello#331]
## bug?

Yes?
### Expected behavior

Should not happen.
### Actual behavior

I see PROPERTIES and END in the description:
![selection_002](https://cloud.githubusercontent.com/assets/1724788/15944772/f8109346-2e43-11e6-8f11-ac3c4d3ff365.png)

What really happened?
Not really sure.
### Steps to reproduce the behavior

I will try to find out!

**Comment by ardumont** [comment]
What does your card looks like before and after your sync operations?

To appear there, the :PROPERTIES: and :END: are mixed with description.
Which means that those properties are indented by 2 spaces, am i correct?

Are :PROPERTIES: :END: automatically created when you add a card?

--

One does wonder, what's the value of `kill-whole-line` (<kbd>M-: kill-whole-line RET</kbd>)
#328 revealed some discrepancies in behavior due to that custom variable.
And i wonder if it's not at play here as well.

Thanks for your feedback.

Cheers,
