### ISSUE TITLE
Dashes in org-trello property names breaks org's search functions

### ISSUE THREAD

**Issue by Gastove** [org-trello/org-trello#334]
I'm not sure if this is a bug report; it seems like to to me, but I do not know your intentions with how org-trello ought behave. 

The difficulty is this: Let's say I have a heading with a property, so:

```
* Test Heading
  :PROPERTY:
  :foo: bar
  :end:
```

Using the org agenda, I can do a quick search, using that property. I would do it like so:
1. Call `org-agenda`, which brings up the agenda dispatcher, then select `m` for a `TAGS/PROPS` query. 
2. Use the query string `foo="bar"`. 

Org will give me back a buffer with every heading where the `foo` property has value `bar`. Handy dandy. Frequently used queries can even be baked in to the agenda dispatcher, allowing very tidy access to specific lists of entities from an org doc.

Where this would be extremely handy in `org-trello` goes like this: my work has a huge trello board. I want a quick, easy way to see all the cards I'm currently on. I think, I'll use my old friend, the agenda dispatcher  with a property query, like so:

```
M-x org-agenda <RET> m <RET> orgtrello-users="gastove"
```

And here we fall apart. Property names with dashes are not considered valid by the agenda system and are ignored. Instead of getting a view into what I need to do, I cannot sort or filter my trello entities at all. 

So, the question is: would this behavior be welcome in org-trello? I'm open to taking a try at a PR to enable this myself, but would not be upset if someone else wanted to do it. (It's not yet clear to me if property values are ever interned as symbols. If they're only ever read and written as strings, then fixing this could be as easy as switching dashes to underbars and calling it a day. If the string name of a property gets interned as a symbol, some munging would be needed to go back and forth.)

**Comment by ardumont** [comment]
Hello,

Thanks for the to-the-point report.

> I'm not sure if this is a bug report; it seems like to to me, 

It looks like it.

> but I do not know your intentions with how org-trello ought behave. 

Well, do not break org-mode user's habits :D

But org-mode is quite huge and i don't know half of its abilities.
My point being, it's possible this rule is broken from time to time.
Thanks to benevolent user such as yourself, i'm being made aware of some awesome abilities.

> The difficulty is this: ...
>... from an org doc.

Like i said 'Awesome'.

> And here we fall apart. Property names with dashes are not considered valid by the agenda system and are ignored. Instead of getting a view into what I need to do, I cannot sort or filter my trello entities at all. 

To check your assertion, you could locally *break* your org-trello buffer by replacing every 'orgtrello-' key with 'orgtrello_' or whatever separator your prefer (or none) to check that you get back the appropriate behavior. 

If this works, I'm interested by that result :D

> So, the question is: would this behavior be welcome in org-trello?

Sure.

> (It's not yet clear to me if property values are ever interned as symbols. If they're only ever read and written as strings, then fixing this could be as easy as switching dashes to underbars and calling it a day. If the string name of a property gets interned as a symbol, some munging would be needed to go back and forth.)

In org-trello, there must be constants in org-trello-setup.el for that, e.g. https://github.com/org-trello/org-trello/blob/master/org-trello-setup.el#L44.

Also, there are tests so everything will get broken during an eventual migration (changing from dash to underbar for example) until it's fixed.

On the top of my head, there are 2 things to think of if any change is planned:
- org-trello buffer migration (from old format to new)
- barf, some integration tests which will be painful to fix (since there are checksums computations based on the buffer's content).

Cheers,

**Comment by Gastove** [comment]
ACK! Sorry. Got badly swamped. Coming back to this, will dig in, try to be more helpful.

**Comment by Gastove** [comment]
So! Finally had time to check in on this. And: if I change every `orgtrello-users` property to instead be `orgtrello_users`, property search begins working again. 

...but of course, then sync breaks, because no properties have the correct names ;-P

I'll start digging in to this some. If I'm lucky, perhaps there's a tidy way to go between symbols and strings, such that properties are printed in to the file with underbars but are converted to kebab-case on read? Sure to be fun ;-P

**Comment by ardumont** [comment]
Those properties are now using an `_` so this should be fixed ;)
