### ISSUE TITLE
change location of .trello folder

### ISSUE THREAD

**Issue by zeltak** [org-trello/org-trello#344]
Hello,

Can you please provide the following information?

Thanks in advance.

### What do you want?
is it possible to set a user define location for the .trelo folder? i usually have .emacs.d/ under git control and dont want all my tokens public :)

best

Z

**Comment by ardumont** [comment]
Hello,

Please beware the typos, i did not understood immediately what this was about.
It did not hit me immediately that 'chane' was 'change', i imagined it was some word i did not know since i'm not a native english person.

Also, can you please remove what's not necessary in your report (all the unanswered question and all)?

Thanks in advance.

> is it possible to set a user define location for the .trelo folder? 

Well, it's not a user custom so no, not properly (yet?).
Here is the definition https://github.com/org-trello/org-trello/blob/master/org-trello-setup.el#L162.

> i usually have .emacs.d/ under git control and dont want all my tokens public :)

Right, **.gitignore** will help with that.

Although, I guess you could try to change the value with something like that in your ".emacs" or ".emacs.d/init.el" configuration somewhere:

```lisp
(require 'org-trello)
(setq org-trello--config-dir "/some/other/preferred/folder")
```
Note: You should have the read/write access to that folder for the user running emacs.

And then move your user.el file in that folder.
I did not check that behavior though.

Cheers,

**Comment by zeltak** [comment]
thx that did the trick!

best

Z

**Comment by ardumont** [comment]
Hello,

> thx that did the trick!

Awesome!
but which one?

Cheers,

**Comment by zeltak** [comment]
oh sorry this one :)

```(setq org-trello--config-dir "/some/other/preferred/folder")```

**Comment by ardumont** [comment]
Thanks
