### ISSUE TITLE
org-trello not found

### ISSUE THREAD

**Issue by bimawa** [org-trello/org-trello#345]
Hello,

After long time i'm work correctlry but after relauch spacemacs catch error `:Error loading .spacemacs: (file-error "Cannot open load file" "No such file or directory" "org-trello")`
and org-trello not work.

### M-x org-trello-bug-report

can't call it.

Thanks for sharing!

Cheers,

**Comment by ardumont** [comment]
> After long time i'm work correctlry but after relauch spacemacs catch error :Error loading .spacemacs: (file-error "Cannot open load file" "No such file or directory" "org-trello")
and org-trello not work.

It cannot be an org-trello related issue.
org-trello has no routine to mess with package or filesystem.

In any case, emacs (or spacemacs) either found the org-trello library and loads it, either it does not and trigger the error you are seeing.

It's either spacemacs related (spacemacs has their way of loading modes in emacs, the layer).
You may have used an org related layer which removed altogether the org-trello modes (after an upgrade). 

Or you made some cleanup in your ~/.emacs.d/elpa/ folder.

Or you changed something in your spacemacs configuration yourself.

Surely, there is something that changed in your emacs before you restarted it.

> bug?

I don't think so.

> can't call it.

Indeed, because org-trello is not installed or has been removed from your system.

Cheers,

**Comment by bimawa** [comment]
@ardumont Thanks Antoine! I try research it.

**Comment by bimawa** [comment]
Damn Finger-broken made micro mistake in `.spacemacs`. Thanks for advice!

**Comment by ardumont** [comment]
> Damn Finger-broken made micro mistake in .spacemacs. Thanks for advice!

Sure
