### ISSUE TITLE
Trello->Emacs sync comment not working

### ISSUE THREAD

**Issue by palaniraja** [org-trello/org-trello#360]
## bug?
Also, I found that the card comment from trello->emacs (C-u org-trello-sync-comment) doesn't work but show `org-trello No comment to delete - skip` message

### Expected behavior

Running `C-u org-trello-sync-comment` after `org-trello-install-board-metadata` (i.e., subsequent changes) should pull updates from trello to local org file.

### Actual behavior

`C-u org-trello-sync-comment` to pull changes from trello  to local org file. This is after `org-trello-install-board-metadata`
And in the mini buffer I see  `org-trello No comment to delete - skip` error.

What really happened?

**Comment by ardumont** [comment]
Hello,

There is some confusion here. <kbd>C-u org-trello-sync-comment</kbd> deletes comment, not sync them. Comments are kept in sync with the card or buffer.
So to sync comments from trello, you need to actually sync back the card/buffer.

And to effectively delete a comment, you need to be on that comment line. Otherwise, you do have the message, no comment to delete.

Regarding the choice of why <kbd>C-u M-x org-trello-sync-comment</kbd> does delete a comment, that may be a sign of a bad api decision. I think I was trying limit the number of commands that org-trello presented to the user...

Cheers,
