### ISSUE TITLE
org-trello's global :PROPERTIES: format doesn't play nicely with a "-*- mode" header

### ISSUE THREAD

**Issue by mexisme** [org-trello/org-trello#369]
# Clarification / Improvement

## Description

The head of each of my org files looks similar to:

```
# -*- mode: org; coding: utf-8-auto-unix -*-
#+LAST_MOBILE_CHANGE: 2015-01-01 09:46:33
#+STARTUP: overview
#+CATEGORY: Notes
#+ARCHIVE: %s_archive::
#+TAGS: @work @home
#+TODO: DOING NEXT WAITING TODO HOLD MAYBE | DONE CANCELLED
#+PRIORITIES: A D C
#+PROPERTY: Effort_ALL: 2min 10min 30min 1hr 2hr 4hr 1day 2day 1wk 2wk 1mon 2mon
#+COLUMNS: %25ITEM(Item){X/} %4PRIORITY(Pri) %9TODO(ToDo) %6Effort %25TAGS
#+TITLE: ToDo
#+AUTHOR: ME
#+EMAIL: me@a.b.c
#+OPTIONS: toc:nil num:nil d:nil H:2
#+INFOJS_OPT: view:overview toc:nil tdepth:0 buttons:t
```

When I tried to install org-trello, it would fail in the `orgtrello-controller--remove-properties-file` function, because the `orgtrello-buffer-global-properties-region` insisted on finding my `#+PROPERTY` (etc) entries in a `:PROPERTIES:` ... `:END:` block.

It looks like it insists on this being at the very beginning of the file, rather than one of the generalised `#+PROPERTY` settings from org-mode.

## Question

Am I misunderstanding how org-trello is designed to work?

This also seems to clash against my needing the mode header on the first line, and also against some of the org-mode advice on adding global properties for each file:
http://orgmode.org/guide/Properties.html#Properties

Is there any plan to adjust to what seems to be the documented style for `#+PROPERTY` config settings?

What are the lines like below intended for?

```
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :orange
#+PROPERTY: :red
#+PROPERTY: :green
#+PROPERTY: :yellow
```

## Why is this better?
- It allows me to use `-*- mode` header in the intended way.

- It seems to integrate better with other org-mode properties.

Thanks

# System information:
```
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-04-22
- org version: 9.1
- org-trello version: 0.8.0
- org-trello path: /Users/willjr/.emacs.d/.cask/25.2/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil
user-error: Minibuffer window is not active
org-trello - Please:
- Describe your problem with clarity and conciceness (cf. https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html)
- Explicit your installation choice (melpa, marmalade, el-get, tarball, git clone...).
- Activate ‘’trace‘’ in logs for more thorough output in *Message* buffer: (custom-set-variables ’(orgtrello-log-level orgtrello-log-trace)).
```

**Comment by ardumont** [comment]
> When I tried to install org-trello, it would fail in the orgtrello-controller--remove-properties-file function, because the orgtrello-buffer-global-properties-region insisted on finding my #+PROPERTY (etc) entries in a :PROPERTIES: ... :END: block.
> It looks like it insists on this being at the very beginning of the file, rather than one of the generalised #+PROPERTY settings from org-mode.

Yes, that's how it's implemented IIRC.
From your expectations, this seems wrong.

The global property drawer was a user idea which sounded completely reasonable at the time (to hide some metadata). Come to think of it, enforcing its use is wrong.
And again, IIRC, once org-trello is installed, removing the :PROPERTIES: and :END: around the org-trello properties is totally fine. org-trello won't raise concern about it for sync.
So, this seems to go your way.

> Am I misunderstanding how org-trello is designed to work?

Probably not, but we may never know.
I never claimed org-trello is perfect though (or me for that matters :)
So, it's totally possible you hit an issue i'm not aware of (it seems that way).
So thanks for raising concerns.

Note: Not being perfect is one reason why it's libre software.
That way, we can improve on it as we use it.

> This also seems to clash against my needing the mode header on the first line,

I don't know about that. I'd need to check (including your link).

>  and also against some of the org-mode advice on adding global properties for each file:
http://orgmode.org/guide/Properties.html#Properties

Well, your link does not specifically talk about global properties though.
Anyway, it seems possible to avoid using a named :PROPERTIES: a possible way (rename it as :ORG-TRELLO-PROPERTIES: or something could be one solution).
I must have used it to avoid having to filter out unrelated org-trello properties, or worse, erase those.

Then again, i'd need to check my assertions here.

> Is there any plan to adjust to what seems to be the documented style for #+PROPERTY config settings?

Well, as usual, if the issue is confirmed, yes.
Either, I will do it when i found the time to or someone can propose a tested PR.

> What are the lines like below intended for?

Those are for mapping between org-mode's tag with trello's colorized labels.
In your case, you seem to not have overriden the default values (empty - this is totally fine btw :)
Looks like a missing information on the [documentation site](http://org-trello.github.io).

Cheers,

**Comment by mexisme** [comment]
Thanks, that's very useful answer.

> Well, your link does not specifically talk about global properties though.

Ugh, sorry about that.
I can't find the one I had, but http://orgmode.org/manual/Property-syntax.html implies

> The global property drawer was a user idea which sounded completely reasonable at the time (to hide some metadata). Come to think of it, enforcing its use is wrong.

If I can, I'll try to find some time to hash out a change, but I always try to ask qu's first!

Would something like this be reasonable?

- Instead of a global `:PROPERTIES:` drawer, use the above (implied) `#+PROPERTY:` style
- Find some other way of avoiding "noise" in the buffer; perhaps hide them in a special "org-trello" task, or at the end of the file?
- When installing / updating the org-trello global properties:  search for all org-trello ones and clean them up, instead of looking for a `:PROPERTIES:` drawer on line 1
- Preferably use built-in org-mode functions for finding + managing properties (I think you largely do, except for using the above `:PROPERTIES:` drawer)

**Comment by ardumont** [comment]
Hello,

> 1. Instead of a global :PROPERTIES: drawer, use the above (implied) #+PROPERTY: style
> 4. Preferably use built-in org-mode functions for finding + managing properties

I think those 2 are the right call (4. being the solution to implement 1.)

> (I think you largely do, except for using the above :PROPERTIES: drawer)

Indeed, i mostly use org-mode's api functions.

Except for the global properties... 
Also for the org-trello checkboxes which, as far as i could tell at the time, did not permit to hold metadata. Note that this is a detail which has nothing to do with the problem at hand :)

Cheers,
