### ISSUE TITLE
Populate an Org file from a prexisting Trello board

### ISSUE THREAD

**Issue by mhlr** [org-trello/org-trello#387]
I am not sure if this is a bug or a feature request,
but when I connect and sync a new org file to a Trello board with cards
it does not copy the the board content into the file.

I would like to start using org-trello with existing boards.
Is there a way to pull all prexisting board content into a file?

thanks
Daniel

**Comment by ardumont** [comment]
Hello,
> I would like to start using org-trello with existing boards. Is there a way to pull all prexisting board content into a file?
...
> I just found out that to sync from Trello I need to pass an argument to org-trello-sync-buffer, i.e. something like C-u 1 C-c o s should do it.

Indeed, as mentioned in the quick start [1] or in the help message (`C-c o h` or <kbd>M-x org-trello-help-describing-bindings</kbd>)

```
...
C-c o s - M-x org-trello-sync-buffer - Synchronize the org-mode file to the trello board (org-mode -> trello). With prefix C-u, sync-from-trello (org-mode <- trello).
...
```

[1] http://org-trello.github.io/quick-start.html

Cheers,

**Comment by ehamberg** [comment]
(Thanks for a great package, @ardumont!)

I was also stuck on this, and (probably since I'm a new emacs user), the behaviour of the `org-trello-sync-buffer` command was very confusing to me (still is!). Why isn't this two separate commands (perhaps with a third command that does both)?

Any way, for future Spacemacs users that find this:
Since `C-u` is taken by evil-mode in Spacemacs, in order to sync _from_ Trello, you need to first press `SPC SPC` to open _helm-M-x_, then find the _org-trello-sync-buffer_ command and here's the important part: press `C-u` before you hitting `return`. :)
